
FROM amazon/aws-glue-libs:glue_libs_4.0.0_image_01


WORKDIR /home/glue_user/workspace

RUN pip3 install --no-cache-dir \
    kafka-python \
    pandas \
    requests \
    pyspark \
    selenium \
    psycopg2-binary \
    sqlalchemy \
    numpy \
    yfinance \
    matplotlib
